language: node_js
node_js:
    - "7"
install:
  - npm install hexo-cli -g
before_script:
  - hexo init ci-test
  - cd ci-test
  - npm install
  - npm install prismjs hexo-generator-search hexo-generator-feed  hexo-helper-qrcode hexo-wordcount --save
  - git clone https://github.com/Halyul/hexo-theme-mdui.git themes/mdui
  - sed -i "s/theme:\ landscape/theme:\ mdui/g" _config.yml
  - sed -i "s/enable:\ true/enable:\ false/g" _config.yml
  - git clone https://github.com/Halyul/theme-mdui-ci.git _ci
  - cp -rf _ci/source source
  - cp _ci/theme/_config.yml themes/mdui
  - cd themes/mdui
  - git checkout -t origin/dev
  - git pull
  - cd ../..
script:
  - hexo clean && hexo g
